### ISSUE TITLE
Please build for Linux and MacOS as well

### ISSUE THREAD

**Issue by ddavidebor** [microsoft/hidtools#10]
Hi,

May I ask you if you could kindly build and release Linux and MacOS binaries as well?

**Comment by matwilli** [comment]
This tool targets the .NET Framework, which is only [supported on Windows](https://learn.microsoft.com/en-us/dotnet/framework/get-started/system-requirements), so binaries for other platforms cannot be produced.

We have no plans to target other .NET versions.
