### ISSUE TITLE
Where to find the correct naming for all the usages?

### ISSUE THREAD

**Issue by ddavidebor** [microsoft/hidtools#11]
Hi,

In the examples I see naming as "Generic Desktop" and "Mouse". Where does this software get these keys and the associated values? I cannot find where the machine-readable hid usage tables this software is getting the data from are

**Comment by matwilli** [comment]
All definitions are from the official [USB-IF HID-WG document for HID Usage Tables](https://usb.org/hid).  This `.PDF` includes (as an embedded-file/attachment) a `.JSON` file with all keys/mappings.

That `.PDF` is downloaded (and embedded in `HidSpecification.dll`) as part of [HidSpecification.csproj](https://github.com/microsoft/hidtools/blob/main/Waratah/HidSpecification/HidSpecification.csproj) compilation.  Then, during execution, the embedded `.JSON` from the embedded `.PDF` is extracted and read
