### ISSUE TITLE
Vendor Pages / Usages

### ISSUE THREAD

**Issue by mgaffigan** [microsoft/hidtools#12]
How can the tool be used to create descriptors which include vendor pages and usages?  Specifying a `usage` or usages by number produces

> Error @ 'usage' (L2) WAR764E75F5: Unknown usage [65315, 1].

Version: WaratahCmd 1.3.0.0
Example wara: 

```
[[applicationCollection]]
usage = [65315,1]

    [[applicationCollection.inputReport]]
        [[applicationCollection.inputReport.variableItem]]
        usage = [65315, 2]
        logicalValueRange = [0, 1]
```
Invocation: `PS> & .\WaratahCmd.exe --source=example.wara`

**Comment by matwilli** [comment]
The vendor usagePage/usageId must each be explicitly defined in the file.  See the [example](https://github.com/microsoft/hidtools/wiki/Waratah-Sections#usagepage)  in the wiki
