### ISSUE TITLE
Member name control

### ISSUE THREAD

**Issue by reinderien** [microsoft/hidtools#15]
We should introduce a `[[settings]]` entry to drop implied suffixes to struct members like `Button`. For backwards compatibility this could not be enabled by default, but would produce more sensible output for the many dozens of HID fields that are one-bit and do not in fact represent buttons.

**Comment by matwilli** [comment]
It's a pattern in Windows ([Win32 APIs](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/hidpi/nf-hidpi-hidp_getbuttons)), that single bit values are referred to as Buttons.  This pattern is maintained in the tool
