### ISSUE TITLE
C compatibility

### ISSUE THREAD

**Issue by reinderien** [microsoft/hidtools#16]
Output is very close to being C-compatible. So far the only thing I've encountered that departs from this is `enum class`. It would be very useful to offer a `[[settings]]` entry to degrade `enum class` to a plain C `enum`, as well as any other output that C would not support.

**Comment by matwilli** [comment]
This is a good idea, but supporting multiple output languages (even similar ones like C/C++) is getting beyond what I can reasonably scope to this project.
