### ISSUE TITLE
HID Usage Tables V.1.3

### ISSUE THREAD

**Issue by urusov-a59** [microsoft/hidtools#2]
Do you plan improve utility for HID Usage Tables V.1.3 (page 0x84/85)

**Comment by matwilli** [comment]
Yes, I certainly plan to include all Usages from the new HUT1.3.

Currently, Waratah includes a copy of the HUT JSON.  The HUT1.3 PDF includes the .JSON as an internal attachment (HidUsageTables.json).  I plan to update Waratah to interrogate the PDF directly for this attachment, and for the user to configure which PDF to interrogate from.  This gives Waratah 'one-source-of-truth', which is the public spec.

**Comment by matwilli** [comment]
I've recently (today) made a [change](https://github.com/microsoft/hidtools/commit/402dfe0b674213664682af5f52cd84ed854a7680) where Waratah will interrogate the PDF directly.  I've also updated the embedded file to be the most recent PDF (HUT 1.3) which will address this Issue.

Closing as Resolved
