### ISSUE TITLE
Copyright violation by republishing the HID Usage Tables?

### ISSUE THREAD

**Issue by bjanders** [microsoft/hidtools#7]
I'm not the copyright holder, so it's not really my business, but still wondering if it is intentional. This repository distributes hut1_3_0.pdf. The document's copyright notice says:

>  THIS SPECIFICATION MAY NOT BE REPUBLISHED EXTERNALLY OR OTHERWISE TO THE PUBLIC.

Does Microsoft have the permission to republish it here?

**Comment by bjanders** [comment]
At least it seems it's not possible to fork this repo without violating the license, I think as a layman (not a lawyer).

**Comment by matwilli** [comment]
Thanks @bjanders, this does strike me as a problem and I appreciate you bringing this up.  I've reached-out to the USB-IF for their guidance, and they are still reviewing it.  I'll respond back to this thread when I hear back, and what a solution could look like.

**Comment by matwilli** [comment]
@bjanders I've heard back from the USB-IF and they agree the PDF shouldn't be included in the repo.  I've modified the build process so it now downloads the PDF at compile-time, mitigating this problem.
